development:
  adapter: postgresql
  encoding: unicode
  database: remote_control_development
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>

test:
  adapter: postgresql
  encoding: unicode
  database: remote_control_test
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>

production:
  adapter: postgresql
  encoding: unicode
  database: remote_control_production
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>