name: CI RSpec Tests

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - '5432'
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: bin/rails db:create db:schema:load

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: bundle exec rspec spec
