name: CI RSpec Tests

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - '5432'
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Preapre Database
        run: bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:@localhost:5432/postgres
        run: bundle exec rails test
